### ISSUE TITLE
Windows Vagrant issue

### ISSUE THREAD

**Issue by JanWerder** [ludumdare/dairybox#2] opened 2015-07-21 22:16 UTC
I followed the instructions to step 3, but I get the following error.

![](http://i.imgur.com/4FtbuuF.png)

Which results in the APCu Extension not being installed (or similar)

![](http://i.imgur.com/5AMMrVL.png)

I'm using a WIndows 8.1 x64 machine

**Comment by mikekasprzak** [comment] 2015-07-21 23:01
Thanks for the report. I haven't had actually tried it on Windows yet. I'm impressed it got that far. ;)

I'll take a look.

**Comment by mikekasprzak** [comment] 2015-07-23 22:12
Okay, it should be fixed now.

Grab the latest version of DairyBox with a `git pull -u`, destroy the old VM with `vagrant destroy` and try `vagrant up` again.

**Closed as completed by mikekasprzak** 2015-07-23 22:12 UTC

**Comment by JanWerder** [comment] 2015-07-23 22:45
Thanks for fixing that, but it throws up another error in a different script now:

![](http://i.imgur.com/OKPsswy.png)

**Comment by mikekasprzak** [comment] 2015-07-24 01:48
That looks like the source code isn't checked out correctly.

In your "www" folder you should see everything you see here:

https://github.com/povrazor/ludumdare

**Comment by JanWerder** [comment] 2015-07-24 07:39
My www folder is identical to the github repo.
I've checked the setup.sh by hand and it matches perfectly.
Any ideas?

**Comment by mikekasprzak** [comment] 2015-07-24 14:23
Hmm. Well, if you'll humor me, can you try checking out a 2nd copy of everything?

First of all, just in case, go to your current DairyBox folder and do a `vagrant halt` just to make sure the VM isn't running. 

Exit out of that folder, then run each of these commands one after the other. Feel free to change `myludumdare`, but keep everything else the same.

```
mkdir myludumdare
cd myludumdare
git clone https://github.com/povrazor/dairybox.git .
cd www
git init
git remote add origin https://github.com/povrazor/ludumdare.git
git fetch
git checkout -t origin/master
vagrant up
```

**Comment by JanWerder** [comment] 2015-07-24 14:44
Ok, did that. I get the same error. But did I get that right, it worked for your test under windows?
I doesn't seem like a windows issue to me, isn't the setup.sh a bashscript executed inside of the VM?

**Comment by mikekasprzak** [comment] 2015-07-24 15:04
Yeah it's working fine on my Windows 7 machine (also 64bit). I'll fire up a Windows 8 machine and see if I can reproduce it there.

And yes, setup.sh is a script that's inside the VM. So long as it can be seen inside the VM, it will run.

You should be able ssh in to the box using `vagrant ssh`. If you browse to `/var/www/` (i.e. `cd /var/www/`) you should be able to see everything that you have in your `www` folder inside the VM (i.e. `ll` or `ls -l`).

**Comment by JanWerder** [comment] 2015-07-24 15:25
So `vagrant ssh` doesn't work on windows without external tools. It trys to use `ssh`, which isn't installed. I got a conenction via `putty`, and found all the dev files in the folders, but I wasn't able to execute the `setup.sh` with the vagrant user, since I don't have the permission.

**Comment by mikekasprzak** [comment] 2015-07-24 15:44
Okay here's a question. Did you install the version of Git from here:

http://git-scm.com/

That will include things like a bash shell, ssh, and other typically Linux tools.

You can use their "Git Bash" program to do things the Linux'y way (which is pretty similar, but I've been testing both `cmd` and `bash` and they're fine on my end).

If you're using a Tortoise GIT or equivalent, I'm not sure if the setup is any different.

It probably wont make much of a difference, but it should explain why `vagrant ssh` wasn't working.

**Comment by JanWerder** [comment] 2015-07-24 15:50
Oh, yes I did, but I didn't add them to the Windows `%PATH%`.
I fixed that now. Same error though.

**Comment by mikekasprzak** [comment] 2015-07-24 15:55
Okay, I'm going to see if I can reproduce this on a Windows 8 machine. Humorously, I have 2 Win 8 machines, and one just died on me. :D 

Is there anything special about your Windows 8.1 machine? Was it a fresh install, was it an upgrade from 8 or 7, etc?

**Comment by JanWerder** [comment] 2015-07-24 15:58
It was a fresh install, so there shouldn't be anything special about it. I'm using the newest VMWare 5.0 version.

**Comment by mikekasprzak** [comment] 2015-07-24 16:01
You mean VirtualBox 5? :)

**Comment by JanWerder** [comment] 2015-07-24 16:02
:) oh sorry, of course I do

**Comment by mikekasprzak** [comment] 2015-07-24 16:41
Okay, it looks like I am having problems with Vagrant on Windows 8 (different problems). I'm guessing some sort of Firewall cleverness Microsoft does. Still working on it.

**Comment by JanWerder** [comment] 2015-07-27 13:26
Any luck? Will try again in a few days with Windows 10, but I'm unsure the results will differ.

**Comment by mikekasprzak** [comment] 2015-07-27 14:42
Not yet. I'll try taking another stab at it tonight.

**Comment by mikekasprzak** [comment] 2015-07-27 15:12
Actually I just got it working. Again my error was different than yours, but I noticed when I would run VirtualBox, it told me of some 64bit incompatibility.

In my case, I had to disable Hyper-V to get it working.

I did this from `Settings->Control Panel->Programs and Features->Turn Windows Features on or off (in the sidebar)`, by unchecking Hyper-V.

Another suggestion I read was making sure Intel Virtualization is enabled in your bios, but it was for me.

**Comment by JanWerder** [comment] 2015-07-27 17:36
I don't have the Hyper-V checked and my Virtualization is enabled. I can run any Virtual Box just fine. It really is a strange situation. I tried ssh'ing onto the machine again and still can't execute the script.sh. Not a chance. No chmod +x or sudo bash changed that. I'm out of ideas

**Comment by mikekasprzak** [comment] 2015-07-27 20:48
Yeah this is so strange.

Can you print it perhaps? i.e. `cat /var/www/scripts/setup.sh`?

Well setup.sh or not, at the very least since we're this far, the webserver should be running, but you're just missing all the extra services (ports 8080-8089), and the data in the database.

Try connecting to http://192.168.48.48

If that works, it should tell us a little bit about what's wrong. I would think since you can't execute setup.sh that maybe you can't read either (i.e. cat). But if we get a bunch of PHP errors, then this is very confusing. :)

**Comment by JanWerder** [comment] 2015-07-27 21:49
A normal cat works:

![](http://i.imgur.com/girnJYy.png)

When I try to execute it it denies the permission:

![](http://i.imgur.com/f0Rh49D.png)

And the webpage complains about the apcu extension:

![](http://i.imgur.com/148QW3x.png)
